name: "Install Dependencies"
description: "Action to build the project dependencies from the main versions"
inputs:
  python_version:
    required: true
    type: string
    default: "3.10.12"
  poetry_version:
    required: true
    type: string
    default: "1.8.3"

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry_version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
        cache: "poetry"
        cache-dependency-path: ./model/poetry.lock
    - name: Try
      run: source .venv/bin/activate
      run: poetry run ruff check
      work directory: ./model
      shell: bash
    - name: Install Dependencies
      run: poetry lock --no-update -C model && poetry install --no-root -C model
      shell: bash