name: format
on: 
  push:
   branches:
    - test
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: hello
      run: ./shell

    - name: black
      uses: rickstaa/action-black@v1
      with:
        black_args: ". --diff"

    - name: ruff 
      uses: chartboost/ruff-action@v1