name: format

on: 
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "taihe/**"
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: format check
      run: bash shell.sh