name: format
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: ruff 
      uses: chartboost/ruff-action@v1

    - name: black
      uses: rickstaa/action-black@v1
      with:
        black_args: ". --check"