name: test

on: 
    [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install_independencies/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  ./.github/workflows/actions/install_independencies/
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64
      - name: Test and Report Coverage
        run: scripts/test

  all_tests_passed:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests passed"