name: tests

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install_independencies/

  ruff:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  ./.github/workflows/actions/install_independencies/
      - name: run ruff
        run: poetry run ruff check

  black:
    needs: setup
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses:  ./.github/workflows/actions/install_independencies/
        - name: run balck
          run: poetry run black --diff

  all_checks_passed:
    # Used to easily force requirements checks in GitHub
    needs:
      - ruff
      - black
    runs-on: ubuntu-latest
    steps:
      - run: echo "All checks passed"