name: tests

on: 
    push:
     branches:
      - test
    pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install_independencies/

  check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  ./.github/workflows/actions/install_independencies/
      - name: Make the script files executable
        run: chmod +x check
      - name: check format
        run: ./check

  all_checks_passed:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - run: echo "All checks passed"