name: tests

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install_independencies/

  checks:
    needs: setup
    runs-on: ubuntu-latest
    name: ${{ matrix.quality-command }}
    strategy:
      matrix:
        quality-command:
          - black
          - ruff
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install_independencies/
      - name: run ${{ matrix.quality-command }}
        run: make ${{ matrix.quality-command }}

  all_checks_passed:
    # Used to easily force requirements checks in GitHub
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
      - run: echo "All checks passed"