name: tests

on: 
    push:
     branches:
      - test
    pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/install_independencies/

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  ./.github/workflows/actions/install_independencies/
      - name: Install Dependencies
        working-directory: model
        run: poetry install --no-root
  #       # shell: bash

  # check:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses:  ./.github/workflows/actions/install_independencies/
      - name: Make the script files executable
        run: chmod +x scripts/check
      - name: prepare environment
        working-directory: model
        run: poetry shell 
      - name: check format
        working-directory: model
        run: ../scripts/check

  all_checks_passed:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - run: echo "All checks passed"